version: '3'
services:
  web:
    environment:
      - MONGO=${MONGO}
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - DB=${DB}
      - DBUSER=${DBUSER}
      - DBPASSOWRD=${DBPASSOWRD}
    build:
      context: .
      dockerfile: Dockerfile
    image: peresadaoleg/olegperesada:${APPVEYOR_BUILD_VERSION}-bot
    restart: always
    ports:
      - "5000:80"
    depends_on:
      - mongo
  mongo:
    image: mongo:4.2.0-bionic
    restart: always
    volumes:
      - ~/data/db:/data/db:rw
    ports:
      - "28017:27017"